### PR TITLE
Added weighted_mean function to central.py

### PR DESCRIPTION
**Pull request by Spedi**
These are the changes made to the `central.py` file:

- Added a new function, `weighted_mean`, that calculates the weighted mean of a given data and weights lists.
- Added a new test for the `weigthed_mean` function, which gets in input the already present `data` lists and a new `weigths` list, necessary to do the calculations.
- Corrected some typos and made some styling changes (Nothing too fancy, just some blankspaces), as advised by the PyCharm Editor.

### CODE REVIEW

**Review by 0gregory0 — CHANGES_REQUESTED** [review]
Great work with the pull request Spedi! The weighted mean was well implemented, and thank you very much for the grammar corrections and making the code neater.

However, I really don't understand what the .iml and .xml files do. Is there a chance that they can be gitignored if they don't affect the working of the package?

I must apologize for taking long to review your pull request. I got busy and fell sick, and I only work on Probstatipy in my free time.

**Comment by Spedi** [comment]
Hi there!
Don't worry about answering time, hope you're good and healthy now!
I'm not sure what those files are either, they may be some byproduct of the `git push` command or something like that, as I didn't add them manually by myself.
What do you think we can do? Is there anything that'll be helpful that I can do?

**Comment by 0gregory0** [comment]
I'm doing well now, thanks for asking.
Looking at the file structure, I've noticed that all these extra files are stored in the .idea folder, which I'm guessing was automatically created by your IDE to store metadata. It should have been ignored by including the file name in the .gitignore file.

Try following these steps:

**1. Untrack the folder:** 
Open the terminal in the root folder of the ProbStatipy project (the folder containing the .idea and the src folders) and run the following command:
```bash
git rm -r --cached .idea/
```
This should alert git to stop tracking this file.

**2. Ignore the folder:**
Now we ignore this folder. Open the .gitignore file (in the root folder not in the .idea folder) and add .idea to the list of folders to be ignored. On a new line, type: 
```
.idea/
```
This should tell git that we don't want to track this folder in future commits. 

> Tip: When working on other projects, be sure to ignore this folder along with any folder that you feel will be unnecessary to track by creating a .gitignore file, or adding them to one if it already exists.

**3. Commit the changes:**
In the terminal again, stage and commit these changes with the following commands:
```bash
git add .
```
```bash
git commit -m "Untrack .idea folder"
```
**4. Push the changes**
Still in the terminal, push the changes by running this command. Be sure to include the branch name of your branch that is associated with this pull request for the changes to reflect here.
```bash
git push origin your_branch_name
```


I hope that this works. Try it out and let's see.

**Comment by Spedi** [comment]
Thank you so much for your patience and help, this info is gold for future reference!
I did what you said and pushed the changes, let me know if everything is as it should be in the first place, thank you again!

**Comment by Spedi** [comment]
If you see changes in the `.idea/gitignore` folder they are probably just blank spaces or newlines, because I forgot that I needed to check for the root `gitignore`, that's why they appear on the commit too.

**Comment by 0gregory0** [comment]
Great work. Thank you for your patience as well. Let me merge the PR. If the .idea folder shows up, I'll pull the changes, delete it from my end and then commit. I didn't want to ask you to delete it because your IDE may be relying on it. But let me first merge and see.

**Pull request merged**
